### ISSUE TITLE
A bit CPU heavy?

### ISSUE THREAD

**Issue by nigels-com** [sykeben/RasDash#5] opened 2019-03-31 12:19 UTC
![Screenshot from 2019-03-31 22-18-59](https://user-images.githubusercontent.com/545677/55288960-0e1e1b80-5403-11e9-9768-62a075f60871.png)

**Comment by sykeben** [comment] 2019-03-31 16:40
Is it intense while just running? Or does it get intensive while the dash is open in a browser?

**Comment by nigels-com** [comment] 2019-03-31 22:38
Yeah, just when there is a tab still open.  And the more tabs, the more CPU usage.

**Comment by sykeben** [comment] 2019-04-01 17:28
Hmm. I believe it’s the web server portion of the program sending stats to the browser. While the dash is open, the browser requests api data every second. I don’t think I can fix this as it may be an issue with the web server.

**Comment by perkinsjr** [comment] 2019-04-07 01:05
To potentially fix this issue:

You need to stop using 
// Make dash periodically update every second.
window.setInterval(periodicUpdate, 1000); 

The problem with this is that it will fire regardless if the prior call has been completed, which causes queuing and then you fire more and more. 

You could do something like this:

                       `const setIntervalAsync = (fn, ms) => {
                        fn().then(() => {
                        setTimeout(() => setIntervalAsync(fn, ms), ms);
                              });
                               };

                          setIntervalAsync(() => (periodicUpdate, 1000);`

Obviously untested code but then this would, then fetch it every second or every second after it is complete. Should reduce CPU. if you don't have time I can do a pull and test it out let me know!

**Comment by sykeben** [comment] 2019-04-07 20:23
Ill create a branch and test this, thanks for the great tip!

**Comment by sykeben** [comment] 2019-04-07 20:48
The line `fn().then(() => {` is throwing a type error as the browser is saying it isn't a function. I've tried a few things, but can't seem to get it to work, what do you think is going on?

**Comment by perkinsjr** [comment] 2019-04-07 21:03
Probably a problem with the async function that I wrote on the fly. Give me a little time I can quickly change it against the code and get back to you

**Comment by sykeben** [comment] 2019-04-07 21:42
I have merged your pull request (#7) into the [performance-upgrade-0](https://github.com/sykeben/RasDash/tree/performance-upgrade-0) branch and will test it now.

**Comment by sykeben** [comment] 2019-04-07 22:06
![Capture](https://user-images.githubusercontent.com/33205078/55690425-8898ef00-595f-11e9-8009-1619a2252472.PNG)

Good news! The code from @perkinsjr's pull request (#7) seems to have fixed the problem! I have merged [performance-upgrade-0](https://github.com/sykeben/RasDash/tree/performance-upgrade-0) into [master](https://github.com/sykeben/RasDash/tree/master) and created a [new release](https://github.com/sykeben/RasDash/releases/tag/0.3.1).

Thank you all for your help, the issue is now closed.

**Closed as completed by sykeben** 2019-04-07 22:06 UTC
Labels: bug, good first issue
